# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # Define the server VM
    config.vm.define "server" do |server|
        server.vm.box = "ubuntu/focal64" # Ubuntu 20.04
        server.vm.hostname = "server"
        server.vm.network "private_network", ip: "192.168.56.10"
        
        # Provisioning steps for the server
        server.vm.provision "shell", inline: <<-SHELL
        sudo apt update
        sudo apt install -y nginx squid varnish ufw
        SHELL
    end
    
    # Define the client VM
    config.vm.define "client" do |client|
        client.vm.box = "ubuntu/focal64" # Ubuntu 20.04
        client.vm.hostname = "client"
        client.vm.network "private_network", ip: "192.168.56.20"
    
        # Provisioning steps for the client (minimal setup)
        client.vm.provision "shell", inline: <<-SHELL
        sudo apt update
        sudo apt install -y curl
        SHELL
    end
    
    end
    
    