apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: webserver
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
  replicas: 3

