apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
    env: uat
spec:
  containers:
  - name: web
    image: nginx:1.0.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
